### PR TITLE
Issue/85 off wrong path

### LINKED ISSUE #85: When unsubscribing through web sockets, wrong subscription removed.

### PR DESCRIPTION
**Pull request by JohanvdWest**
Fixes #85.

This would send the unsubscribe for the right path, but when the time came to splice it from the array the listener array would be pointing to the wrong path.

### CODE REVIEW

**Comment by JohanvdWest** [comment]
Important part is line 795 of new file.

File: lib/client/base.js [hunk 1]
```diff
@@ -1,889 +1,901 @@
...
+  HappnClient.prototype._offListener = function (listenerId, done) {
+    var _this = this;
 
-	for (var channel in _this.events){
-		var listeners = _this.events[channel];
+    forEach(_this.events, function (listeners, channel) {
 
-		if (!listeners)
-			return done();
+      if (!listeners)
```
Comment (JohanvdWest) [inline lib/client/base.js]: This seems unnecessary now. Going to remove it.

File: lib/client/base.js [hunk 2]
```diff
@@ -1,889 +1,906 @@
...
-			} else return true;
-		});
-	}
-};
+    function doRemoteOff(channel, listeners, listener) {
+      _this._remoteOff(channel, 1, function (e) {
+        if (e)
+          return done(e);
+        // Find the correct listener at the time of splice as the array could have changed.
+        listeners.splice(listeners.indexOf(listener), 1);
```
Comment (HaroldStruwig) [inline lib/client/base.js]: We should first check:
```javascript
(listeners.indexOf(listener) !== -1)
```
