### PR TITLE
Issue 157

### LINKED ISSUE #157: After a reconnect-scheduled, if the login times out, we never connect again
```
2017-03-21 20:51:12.008 [ INFO] - 1624938ms	satinnape_Ey8B9VpKM (happnerEndpoint) happner-endpoint reconnect/scheduled
2017-03-21 20:51:38.473 [ERROR] - 26468ms	client (HappnClient) unhandled error Error: api request timed out action: login
    at Object.<anonymous> (/node_js/app/node_modules/happn/lib/client/base.js:691:29)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
2017-03-21 20:51:38.482 [ERROR] - Error: api request timed out action: login
    at Object.<anonymous> (/node_js/app/node_modules/happn/lib/client/base.js:691:29)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
```

### PR DESCRIPTION
**Pull request by JohanvdWest**
Fix #157

### CODE REVIEW

File: lib/client/base.js [hunk 1]
```diff
@@ -745,9 +745,16 @@
...
 
+    if (!this.reconnectAttempt) this.reconnectAttempt = 0;
+    var reconnectAttempt = ++this.reconnectAttempt;
+
     _this.authenticate(function (e) {
+      if (_this.reconnectAttempt != reconnectAttempt) return; // this is not the last attempt, ignore it
 
-      if (e) return _this.handle_error(e, 3);
+      if (e) {
+        if (e.message && e.message.indexOf('api request timed out action') == 0) return _this.reconnect();
```
Comment (JensEggers) [inline lib/client/base.js]: 2 comments
- since this is a recursion, probably better to use setImmediate() to limit call stack depth
- is there a possibility of endless retries interfering with shutdown, or is this taken care of at a lower level?

File: lib/client/base.js [hunk 2]
```diff
@@ -745,9 +745,16 @@
   HappnClient.prototype.reconnect = function (options) {
     var _this = this;
 
+    if (!this.reconnectAttempt) this.reconnectAttempt = 0;
+    var reconnectAttempt = ++this.reconnectAttempt;
+
     _this.authenticate(function (e) {
+      if (_this.reconnectAttempt != reconnectAttempt) return; // this is not the last attempt, ignore it
```
Comment (JohanvdWest) [inline lib/client/base.js]: I am not sure about this. This happens if request 1 is timing out and we have a reconnect. Request 2 is triggered before 1 times out. 2 is successful, but 1's timeout causes 3.

File: lib/client/base.js (hunk 1 above)
Comment (JohanvdWest) [inline lib/client/base.js]: Can't do setImmediate, this is used in the browser as well. The function is async, so don't see this as a possibility.
Adding a test for 2.

Comment (JensEggers) [inline lib/client/base.js]: of course, quite right

File: lib/client/base.js (hunk 2 above)
Comment (JensEggers) [inline lib/client/base.js]: prob does no harm since we might get an old response after timing out and retrying

Comment (JensEggers) [inline lib/client/base.js]: however we could also consider simply using a late response received after retrying

File: lib/client/base.js [hunk 3]
```diff
@@ -518,10 +518,7 @@
     });
 
     function handleLoginCallback(e) {
-      if (e) {
-        if (_this.pubsub && _this.pubsub.destroy) _this.pubsub.destroy();
-        _this.pubsub = null;
-      }
+      // JW - Reversing this change. This should be handled by the user of this client.
```
Comment (JohanvdWest) [inline lib/client/base.js]: happner/happner#272 created

File: lib/client/base.js (hunk 2 above)
Comment (JohanvdWest) [inline lib/client/base.js]: The issue is more that a previous one was still timing out, so we might have reconnected, but we reconnect again.

I think I've resolved it cleaner now.

File: lib/client/base.js (hunk 1 above)
Comment (JohanvdWest) [inline lib/client/base.js]: Thank goodness for the test. Caught a shutdown issue on the retries.

**Comment by JohanvdWest** [comment]
Any more comments?
